### GET ALL USER
GET http://localhost:3000/api/users

### CREATE USER
POST http://localhost:3000/api/users/createUser
Content-Type: application/json

{
    "username" : "Maibok",
    "password" : "StrongPassMakMak",
    "firstname" : "Nai",
    "lastname" : "Num"
}

### FAILED CREATE USER TEST
POST http://localhost:3000/api/users/createUser
Content-Type: application/json

{
    "username" : "",
    "password" : "StrongPassMakMak",
    "firstname" : "Nai",
    "lastname" : "Num"
}

### GET USER ID 1
GET http://localhost:3000/api/users/1

### GET ALL ROLES
GET http://localhost:3000/api/roles


###  CREATE ROLE TEST
POST http://localhost:3000/api/roles/createRole
Content-Type: application/json

{
    "role_name" : "Moderator"
}
### CREATE ROLE TEST 2
POST http://localhost:3000/api/roles/createRole
Content-Type: application/json

{
    "role_name" : "NewRole"
}

### UPDATE ROLE 3 TEST
PUT http://localhost:3000/api/roles/updateRole/3
Content-Type: application/json

{
    "role_name" : "Member"
}
### DELETE ROLE 3 TEST
DELETE http://localhost:3000/api/roles/deleteRole/3